### PR TITLE
fix(unsplash): unsplash changing bg ignoring config

### LINKED ISSUE #161: Unsplash bug
If Unsplash is set as wallpaper it download every time new wallpaper on new tab completely ignoring the settings.

### PR DESCRIPTION
**Pull request by lenchq**
## Subtitle of PR

PR to fix #161 
This fixes whenever a new tab opened or page refreshed app sets new background 1-3 times completely ignoring current configuration
Also this bug can be found even on https://tab-nine.xsfs.xyz/ (every page refresh background changes)

### Developer Testing Evidence

Evidence of the PR is in action in the section below.

- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Edge

### Firefox

[Evidence](https://imgur.com/a/IVzsxUb)

### CODE REVIEW

**Comment by the-wright-jamie** [comment]
Ooo thank you! I will merge this when I come back after Christmas. Thank you for fixing this, it didn't come up duing dev testing but it came up a few days after release and I couldn't figure it out.

**Comment by lenchq** [comment]
Any updates on this? It's getting really annoying living with this bug on firefox because i can't install extension without official signature

**Comment by the-wright-jamie** [comment]
Yeah I'm really sorry, to try and regain your trust I will take a look tonight and get a fix out for you. I'll take a look at the other PRs too. Thank you for your patience - I've been bogged with problems IRL as well as doing work for a private client.

**Comment by the-wright-jamie** [comment]
Awesome work on this, tested on local and happy to merge! Thank you very much, this one was bugging me too.

**Comment by the-wright-jamie** [comment]
It seems like new tab isn't working properly still, flicks on the last image before loading new, would like to get down to the bottom of that at some point - but I think that behaviour is present upstream too

**Comment by lenchq** [comment]
Seems strange, I will check on this on the week, btw could you provide info of your environment for me, to test?

**Comment by the-wright-jamie** [comment]
Windows 11 on Chrome Latest release (hope that's enough info - if not I'll get you some more system info), might have been because of #147 - there was change to this area in there - I tried reverting the change but it was still happening.

**Pull request merged**
