### PR TITLE
Random Quotes and Failed Image Fetching Handling

### LINKED ISSUE #135: [Suggestion] Alternatives to 'They Said So'
Hello!
I've been using this extension for a while and I can say it's a great successor to Tabliss. While I believe that, I wanted to help on something, and decided to find an alternative to They Said So.

### Number 1: Quotable

[Quotable](https://github.com/lukePeavey/quotable) is an Open-Source API, which I can guarantee it's a plus for at least some of you. The only problem is that it has a rate limit of 180 requests per minute. So if so many people are using it, ~~that would be an issue.~~ Future Self: I was wrong.

### Number 2: API Ninjas

[API Ninjas](https://api-ninjas.com/) is an API that has over 78 data APIs. This is perfect if quotes isn't the only thing you want to add.
And even if quotes is the only thing you want, there's so many of them. _I think that's only a plus in my book._
It's sadly not Open-Source, so there's a chance they might go the same way as They Said So. But for now that doesn't seem to be the plan.

And that's all I could find! If there are other APIs I missed, feel free to tell me in the comments.
_Man, I feel like a weirdo for focusing so much on quotes._

### PR DESCRIPTION
**Pull request by 7Pawns**
## Subtitle of PR

Added support for Quotable Random Quotes and handled failed image fetches.
Resolved #135 

### Developer Testing Evidence

Evidence of the PR is in action in the section below.

- [x] Tested in Chrome
- [x] Tested in Firefox
- [x] Tested in Edge

## Evidence
You can see we aren't getting any image fetched yet no error thrown

### Chrome
image

### Firefox
image

### Edge
image

### CODE REVIEW

**Comment by 7Pawns** [comment]
Quotable has may tags for images so it's not ideal to list them all in the ui, need to think of a future solution. Probably a tag search will be better

**Comment by the-wright-jamie** [comment]
I see your PR, I'll see if it can be merged when I have a chance

**Comment by 7Pawns** [comment]
@the-wright-jamie hi is this going to be merged?

**Comment by the-wright-jamie** [comment]
Hopefully. I'm currently working through some long running real life events and I regretfully have not had the time to review recent PRs. 

I hope to be fully operational again in around 2 weeks time. I understand that this is frustrating, but I appreciate your patience as well as the time and dedication that went into this PR. Please bear with me as I get back up to speed, thank you.

**Comment by 7Pawns** [comment]
@the-wright-jamie Any update?

**Comment by the-wright-jamie** [comment]
Hey @7Pawns, apologies for leaving you in the dark.

I made [an issue](https://github.com/the-wright-jamie/tab-nine/issues/160) talking about temporary development suspension for the holidays. At the time of my previous comment, I was in the middle of moving flats. I hope to return gradually over January next month. I won't be hitting the ground running, but the first priority will be to test PRs and I hope to get to yours as one of the first.

I appreciate your patience and contribution to the project, and I wish you a Merry Christmas (or Happy Holidays if you don't observe Christmas) and a very, very Happy New Year. I will see you up ahead!

**Comment by the-wright-jamie** [comment]
I will try and get a look at this tonight, sorry for the long wait and thank you for you patience.

**Comment by the-wright-jamie** [comment]
Looks good, thank you very much for this and again apologies it took so long to get to you. I hope in future to have a better process for evaluating PRs. Will merge now

**Pull request merged**
